export { default as Header } from "./Header/Header";
export { default as Footer } from "./Footer/footer";
export { default as MainBanner } from "./MainBanner/MainBanner";
export { default as PopularListing } from "./PopularListing/PopularListing";
export { default as BookingSteps } from "./BookingSteps/BookingSteps";
export { default as Slider } from "./Slider/Slider";
export { default as Testimonials } from "./Testimonials/Testimonials";
export { default as Cards } from "./Card/Card";
export { default as Modal } from "./Modal/Modal";
